### ISSUE TITLE
Calculator reset glitch

### ISSUE THREAD

**Issue by TheTrueWAN** [numworks/epsilon#1992]
This only works on the calculator and is likely a combination of hardware and software fault:
I have found that the numworks calculator will reset itself; deleting all data (scripts, functions, variables, etc.)
this is achieved by:
making a "complicated" graph (x^2+y^2 = 16 a circle works)
pressing the back button while it renders the graph
This does not work on the simulation because the graph loads faster when it has access to more processing power, and so there is no problem there.
I have also found this is the case sometimes when using Python's turtle; I believe it is an issue with how the calculator handles needing more memory than it can access. 
I have done this on two different calculators; so it probably is not just my own calculator acting up
Thank you for your time

**Comment by TheTrueWAN** [comment]
version 19.5.0 or 03.43 or bb3baa
Serial number LwA1ABlRMTIwMzE0
FCC ID 2ALWP-N0110

I'm sorry that I cannot provide footage; but here is how I did it:
go to the grapher
plot the circle x^2+y^2=16
then go to the graph
select navigate
press left and back button in quick succession.
It appears to only work some of the time; I reset my calculator using this
glitch just now (I didn't record it; sorry), but couldn't do it again
immediately after; My guess is that it has something to do with memory that
accumulates with use/time; as I suggested on git hub; although I haven't
looked deeply into the problem. I have also found this to happen a twice
while running python programs on the calculator
I will look into recording the glitch later
thank you for your time

**Comment by Miniontoby** [comment]
I am too, but only with really large and big functions and then exactly the same as the others with the back button

**Comment by M4xi1m3** [comment]
I was able to reproduce the bug and I have a debug probe available, but can't really extract information when the crash occurs (don't have source maps or a way to compile the full firmware and rdp1 prevents me from debugging with SWD).

**Comment by Miniontoby** [comment]
Maybe it has to do with 

> The heap of the Python application has been increased to 64kB and the storage memory has been increased to 42kB.

and/or

> Recursive calculations using Ans in the Calculation application are more efficient and lead to a memory full error less often.

from the version 19 update as listed in here: https://www.numworks.com/calculator/update/version-19/

**Comment by Miniontoby** [comment]
Now with the version 20 I aint just yet able to reproduce the bug anymore.

I think this could be fixed now, but I am not sure. Please verify!

**Comment by mauroriccardi** [comment]
Not fixed yet: it happened to me a few hours ago, pressed the "back" button while it was rendering a graph, and it reset itself erasing everything. 
Version 20.4.0

**Comment by nsi-xyz** [comment]
> Not fixed yet: it happened to me a few hours ago, pressed the "back" button while it was rendering a graph, and it reset itself erasing everything.
> Version 20.4.0

I can't reproduce the bug. Can you give us the function entered?

**Comment by mauroriccardi** [comment]
> > Not fixed yet: it happened to me a few hours ago, pressed the "back" button while it was rendering a graph, and it reset itself erasing everything.
> > Version 20.4.0
> 
> I can't reproduce the bug. Can you give us the function entered?

I fear I cannot: it was an old function from a couple of sessions earlier, insofar as I can recall it was a third degree polynomial, nothing fancy, but I honestly don't think it's relevant. I can tell you what I was doing, anyway. I had switched the calculator off, without exiting the grapher app, then after a while I needed it and I switched it on again, a bit in a hurry, and as it started drawing I pressed the "back" button, possibly a couple of times. I was about to press the "app" button to exit the grapher app, but it reset all by itself. I'm sorry I can't be more specific...it was the second time it happened to me, and looks like some totally random bug.

**Comment by nsi-xyz** [comment]
About a third of the students in my class have encountered this bug, acting like you, but the bug is supposed to have been fixed by Epsilon version 20.3. 🤔

**Comment by artaxxx** [comment]
Indeed, this specific bug is supposed to be fixed in 20.3. If you find how to reproduce it, tell me!

**Comment by BloomyInDev** [comment]
> > > Not fixed yet: it happened to me a few hours ago, pressed the "back" button while it was rendering a graph, and it reset itself erasing everything.
> > > Version 20.4.0
> > 
> > 
> > I can't reproduce the bug. Can you give us the function entered?
> 
> I fear I cannot: it was an old function from a couple of sessions earlier, insofar as I can recall it was a third degree polynomial, nothing fancy, but I honestly don't think it's relevant. I can tell you what I was doing, anyway. I had switched the calculator off, without exiting the grapher app, then after a while I needed it and I switched it on again, a bit in a hurry, and as it started drawing I pressed the "back" button, possibly a couple of times. I was about to press the "app" button to exit the grapher app, but it reset all by itself. I'm sorry I can't be more specific...it was the second time it happened to me, and looks like some totally random bug.

Maybe like that @artaxxx 😀

**Comment by JimboJoe** [comment]
Hello,
I can confirm this bug stills occurs on 20.4.0. It happened already 3 times on my son's calculator which was bought 10 days ago. He has a quite intensive use, though. And we unfortunately couldn't identify a clear reproduction scenario so far, just an intensive use...
