### ISSUE TITLE
Simulator build/run on macOS failing

### ISSUE THREAD

**Issue by blackketter** [numworks/epsilon#2]
Just getting started here...

Trying to build and run epsilon simulator on macOS 10.12.6.  Followed (excellent) instructions on the web site to install the homebrew requirements.  The build appears to succeed but the simulator fails to launch with the following:

```
lucky13:epsilon dean$ make clean;make PLATFORM=simulator;make app_run
CLEAN
HOSTCC  kandinsky/fonts/rasterizer
RASTER  kandinsky/src/small_font.h kandinsky/src/small_font.c
RASTER  kandinsky/src/large_font.h kandinsky/src/large_font.c
BISON   poincare/src/simplify/rules_generation/rules_parser.cpp
HOSTCC  poincare/src/simplify/rules_generation/rules_parser.o
FLEX    poincare/src/simplify/rules_generation/rules_lexer.cpp
HOSTCC  poincare/src/simplify/rules_generation/rules_lexer.o
HOSTCC  poincare/src/simplify/rules_generation/node.o
HOSTCC  poincare/src/simplify/rules_generation/rule.o
HOSTLD  poincare/src/simplify/rules_generation/rulegen
RULEGEN poincare/src/simplify/rules.cpp
FLEX    poincare/src/expression_lexer.cpp poincare/src/expression_lexer.hpp
BISON   poincare/src/expression_parser.cpp poincare/src/expression_parser.hpp
poincare/src/expression_parser.y: conflicts: 7 reduce/reduce
QSTRDAT python/port/genhdr/qstrdefs.generated.h
HOSTCC  escher/image/inliner
INLINER apps/calculation/calculation_icon.cpp
CXX     apps/calculation/calculation_icon.o
INLINER apps/graph/graph_icon.cpp
CXX     apps/graph/graph_icon.o
INLINER apps/on_boarding/logo_icon.cpp
CXX     apps/on_boarding/logo_icon.o
INLINER apps/probability/probability_icon.cpp
CXX     apps/probability/probability_icon.o
INLINER apps/probability/images/binomial_icon.cpp
CXX     apps/probability/images/binomial_icon.o
INLINER apps/probability/images/calcul1_icon.cpp
CXX     apps/probability/images/calcul1_icon.o
INLINER apps/probability/images/calcul2_icon.cpp
CXX     apps/probability/images/calcul2_icon.o
INLINER apps/probability/images/calcul3_icon.cpp
CXX     apps/probability/images/calcul3_icon.o
INLINER apps/probability/images/calcul4_icon.cpp
CXX     apps/probability/images/calcul4_icon.o
INLINER apps/probability/images/exponential_icon.cpp
CXX     apps/probability/images/exponential_icon.o
INLINER apps/probability/images/focused_binomial_icon.cpp
CXX     apps/probability/images/focused_binomial_icon.o
INLINER apps/probability/images/focused_calcul1_icon.cpp
CXX     apps/probability/images/focused_calcul1_icon.o
INLINER apps/probability/images/focused_calcul2_icon.cpp
CXX     apps/probability/images/focused_calcul2_icon.o
INLINER apps/probability/images/focused_calcul3_icon.cpp
CXX     apps/probability/images/focused_calcul3_icon.o
INLINER apps/probability/images/focused_calcul4_icon.cpp
CXX     apps/probability/images/focused_calcul4_icon.o
INLINER apps/probability/images/focused_exponential_icon.cpp
CXX     apps/probability/images/focused_exponential_icon.o
INLINER apps/probability/images/focused_normal_icon.cpp
CXX     apps/probability/images/focused_normal_icon.o
INLINER apps/probability/images/focused_poisson_icon.cpp
CXX     apps/probability/images/focused_poisson_icon.o
INLINER apps/probability/images/focused_uniform_icon.cpp
CXX     apps/probability/images/focused_uniform_icon.o
INLINER apps/probability/images/normal_icon.cpp
CXX     apps/probability/images/normal_icon.o
INLINER apps/probability/images/poisson_icon.cpp
CXX     apps/probability/images/poisson_icon.o
INLINER apps/probability/images/uniform_icon.cpp
CXX     apps/probability/images/uniform_icon.o
INLINER apps/regression/regression_icon.cpp
CXX     apps/regression/regression_icon.o
INLINER apps/sequence/sequence_icon.cpp
CXX     apps/sequence/sequence_icon.o
INLINER apps/settings/settings_icon.cpp
CXX     apps/settings/settings_icon.o
INLINER apps/statistics/stat_icon.cpp
CXX     apps/statistics/stat_icon.o
INLINER apps/code/code_icon.cpp
CXX     apps/code/code_icon.o
INLINER apps/exam_icon.cpp
CXX     apps/exam_icon.o
CXX     apps/calculation/app.o
CXX     apps/calculation/calculation.o
CXX     apps/calculation/calculation_store.o
CXX     apps/calculation/edit_expression_controller.o
CXX     apps/calculation/history_view_cell.o
CXX     apps/calculation/history_controller.o
CXX     apps/calculation/local_context.o
CXX     apps/calculation/scrollable_expression_view.o
CXX     apps/calculation/selectable_table_view.o
CXX     apps/calculation/text_field.o
CXX     apps/graph/app.o
CXX     apps/graph/cartesian_function.o
CXX     apps/graph/cartesian_function_store.o
CXX     apps/graph/function_title_cell.o
CXX     apps/graph/graph/banner_view.o
CXX     apps/graph/graph/curve_parameter_controller.o
CXX     apps/graph/graph/graph_controller.o
CXX     apps/graph/graph/graph_view.o
CXX     apps/graph/list/list_controller.o
CXX     apps/graph/values/derivative_parameter_controller.o
CXX     apps/graph/values/function_parameter_controller.o
CXX     apps/graph/values/values_controller.o
CXX     apps/home/app.o
CXX     apps/home/app_cell.o
CXX     apps/home/controller.o
CXX     apps/hardware_test/app.o
CXX     apps/hardware_test/arrow_view.o
CXX     apps/hardware_test/battery_test_controller.o
CXX     apps/hardware_test/keyboard_test_controller.o
CXX     apps/hardware_test/keyboard_view.o
CXX     apps/hardware_test/led_test_controller.o
CXX     apps/hardware_test/pattern.o
CXX     apps/hardware_test/pattern_view.o
CXX     apps/hardware_test/pop_up_controller.o
CXX     apps/hardware_test/reset_controller.o
CXX     apps/hardware_test/screen_test_controller.o
CXX     apps/hardware_test/usb_test_controller.o
CXX     apps/on_boarding/app.o
CXX     apps/on_boarding/language_controller.o
CXX     apps/on_boarding/logo_controller.o
CXX     apps/on_boarding/logo_view.o
CXX     apps/on_boarding/update_controller.o
CXX     apps/probability/app.o
CXX     apps/probability/calculation/calculation.o
CXX     apps/probability/calculation/discrete_calculation.o
CXX     apps/probability/calculation/left_integral_calculation.o
CXX     apps/probability/calculation/right_integral_calculation.o
CXX     apps/probability/calculation/finite_integral_calculation.o
CXX     apps/probability/calculation_controller.o
CXX     apps/probability/cell.o
CXX     apps/probability/image_table_view.o
CXX     apps/probability/law/binomial_law.o
CXX     apps/probability/law/exponential_law.o
CXX     apps/probability/law/law.o
CXX     apps/probability/law/normal_law.o
CXX     apps/probability/law/one_parameter_law.o
CXX     apps/probability/law/poisson_law.o
CXX     apps/probability/law/two_parameter_law.o
CXX     apps/probability/law/uniform_law.o
CXX     apps/probability/law_controller.o
CXX     apps/probability/law_curve_view.o
CXX     apps/probability/parameters_controller.o
CXX     apps/regression/app.o
CXX     apps/regression/banner_view.o
CXX     apps/regression/calculation_controller.o
CXX     apps/regression/even_odd_double_buffer_text_cell.o
CXX     apps/regression/go_to_parameter_controller.o
CXX     apps/regression/graph_controller.o
CXX     apps/regression/graph_view.o
CXX     apps/regression/initialisation_parameter_controller.o
CXX     apps/regression/prediction_parameter_controller.o
CXX     apps/regression/store.o
CXX     apps/regression/store_controller.o
CXX     apps/sequence/app.o
CXX     apps/sequence/graph/banner_view.o
CXX     apps/sequence/graph/curve_parameter_controller.o
CXX     apps/sequence/graph/curve_view_range.o
CXX     apps/sequence/graph/go_to_parameter_controller.o
CXX     apps/sequence/graph/graph_controller.o
CXX     apps/sequence/graph/graph_view.o
CXX     apps/sequence/graph/term_sum_controller.o
CXX     apps/sequence/graph/vertical_cursor_view.o
CXX     apps/sequence/list/list_controller.o
CXX     apps/sequence/list/list_parameter_controller.o
CXX     apps/sequence/list/sequence_toolbox.o
CXX     apps/sequence/list/type_parameter_controller.o
CXX     apps/sequence/values/interval_parameter_controller.o
CXX     apps/sequence/values/values_controller.o
CXX     apps/sequence/local_context.o
CXX     apps/sequence/sequence.o
CXX     apps/sequence/sequence_store.o
CXX     apps/sequence/sequence_title_cell.o
CXX     apps/settings/app.o
CXX     apps/settings/main_controller.o
CXX     apps/settings/settings_node.o
CXX     apps/settings/sub_controller.o
CXX     apps/shared/banner_view.o
CXX     apps/shared/button_with_separator.o
CXX     apps/shared/cursor_view.o
CXX     apps/shared/curve_view.o
CXX     apps/shared/curve_view_cursor.o
CXX     apps/shared/curve_view_range.o
CXX     apps/shared/editable_cell_table_view_controller.o
CXX     apps/shared/float_pair_store.o
CXX     apps/shared/float_parameter_controller.o
CXX     apps/shared/function.o
CXX     apps/shared/function_app.o
CXX     apps/shared/function_curve_parameter_controller.o
CXX     apps/shared/function_go_to_parameter_controller.o
CXX     apps/shared/function_graph_view.o
CXX     apps/shared/function_graph_controller.o
CXX     apps/shared/function_store.o
CXX     apps/shared/function_expression_cell.o
CXX     apps/shared/function_title_cell.o
CXX     apps/shared/go_to_parameter_controller.o
CXX     apps/shared/initialisation_parameter_controller.o
CXX     apps/shared/interactive_curve_view_controller.o
CXX     apps/shared/interactive_curve_view_range.o
CXX     apps/shared/interactive_curve_view_range_delegate.o
CXX     apps/shared/interval.o
CXX     apps/shared/interval_parameter_controller.o
CXX     apps/shared/list_controller.o
CXX     apps/shared/list_parameter_controller.o
CXX     apps/shared/memoized_curve_view_range.o
CXX     apps/shared/message_controller.o
CXX     apps/shared/new_function_cell.o
CXX     apps/shared/ok_view.o
CXX     apps/shared/range_parameter_controller.o
CXX     apps/shared/regular_table_view_data_source.o
CXX     apps/shared/store_controller.o
CXX     apps/shared/store_parameter_controller.o
CXX     apps/shared/tab_table_controller.o
CXX     apps/shared/text_field_delegate.o
CXX     apps/shared/text_field_delegate_app.o
CXX     apps/shared/values_function_parameter_controller.o
CXX     apps/shared/values_parameter_controller.o
CXX     apps/shared/values_controller.o
CXX     apps/shared/zoom_parameter_controller.o
CXX     apps/statistics/app.o
CXX     apps/statistics/box_banner_view.o
CXX     apps/statistics/box_controller.o
CXX     apps/statistics/box_range.o
CXX     apps/statistics/box_view.o
CXX     apps/statistics/calculation_controller.o
CXX     apps/statistics/histogram_banner_view.o
CXX     apps/statistics/histogram_controller.o
CXX     apps/statistics/histogram_parameter_controller.o
CXX     apps/statistics/histogram_view.o
CXX     apps/statistics/store.o
CXX     apps/statistics/store_controller.o
CXX     apps/code/app.o
CXX     apps/code/editor_controller.o
CXX     apps/code/executor_controller.o
CXX     apps/code/menu_controller.o
CXX     apps/code/program.o
CXX     apps/alpha_lock_view.o
CXX     apps/apps_container.o
CXX     apps/apps_window.o
CXX     apps/battery_timer.o
CXX     apps/battery_view.o
CXX     apps/constant.o
CXX     apps/backlight_dimming_timer.o
CXX     apps/empty_battery_window.o
CXX     apps/exam_pop_up_controller.o
CXX     apps/global_preferences.o
CXX     apps/i18n.o
CXX     apps/led_timer.o
CXX     apps/lock_view.o
CXX     apps/main.o
CXX     apps/math_toolbox.o
CXX     apps/node.o
CXX     apps/suspend_timer.o
CXX     apps/title_bar_view.o
CXX     apps/toolbox_node.o
CXX     apps/usb_timer.o
CXX     apps/variable_box_controller.o
CXX     apps/variable_box_leaf_cell.o
CXX     ion/src/shared/console_line.o
CXX     ion/src/shared/events_keyboard.o
CXX     ion/src/shared/events_modifier.o
CXX     ion/src/shared/events.o
CXX     ion/src/shared/software_version.o
CXX     kandinsky/src/color.o
CXX     kandinsky/src/context.o
CXX     kandinsky/src/context_line.o
CXX     kandinsky/src/context_pixel.o
CXX     kandinsky/src/context_rect.o
CXX     kandinsky/src/context_text.o
CXX     kandinsky/src/framebuffer.o
CXX     kandinsky/src/framebuffer_context.o
CXX     kandinsky/src/ion_context.o
CC      kandinsky/src/large_font.o
CXX     kandinsky/src/point.o
CXX     kandinsky/src/rect.o
CC      kandinsky/src/small_font.o
CXX     kandinsky/src/text.o
CXX     poincare/src/simplify/expression_builder.o
CXX     poincare/src/simplify/expression_match.o
CXX     poincare/src/simplify/expression_selector.o
CXX     poincare/src/simplify/rules.o
CXX     poincare/src/simplify/simplification.o
CXX     poincare/src/simplify/simplification_generator.o
CXX     poincare/src/absolute_value.o
CXX     poincare/src/addition.o
CXX     poincare/src/arc_cosine.o
CXX     poincare/src/arc_sine.o
CXX     poincare/src/arc_tangent.o
CXX     poincare/src/binary_operation.o
CXX     poincare/src/binomial_coefficient.o
CXX     poincare/src/ceiling.o
CXX     poincare/src/complex.o
CXX     poincare/src/complex_argument.o
CXX     poincare/src/complex_matrix.o
CXX     poincare/src/confidence_interval.o
CXX     poincare/src/conjugate.o
CXX     poincare/src/cosine.o
CXX     poincare/src/derivative.o
CXX     poincare/src/determinant.o
CXX     poincare/src/division_quotient.o
CXX     poincare/src/division_remainder.o
CXX     poincare/src/evaluation.o
CXX     poincare/src/expression.o
CXX     poincare/src/expression_lexer.o
CXX     poincare/src/expression_parser.o
CXX     poincare/src/factorial.o
CXX     poincare/src/floor.o
CXX     poincare/src/frac_part.o
CXX     poincare/src/fraction.o
CXX     poincare/src/function.o
CXX     poincare/src/expression_matrix.o
CXX     poincare/src/global_context.o
CXX     poincare/src/great_common_divisor.o
CXX     poincare/src/hyperbolic_arc_cosine.o
CXX     poincare/src/hyperbolic_arc_sine.o
CXX     poincare/src/hyperbolic_arc_tangent.o
CXX     poincare/src/hyperbolic_cosine.o
CXX     poincare/src/hyperbolic_sine.o
CXX     poincare/src/hyperbolic_tangent.o
CXX     poincare/src/imaginary_part.o
CXX     poincare/src/integer.o
CXX     poincare/src/integral.o
CXX     poincare/src/list_data.o
CXX     poincare/src/leaf_expression.o
CXX     poincare/src/least_common_multiple.o
CXX     poincare/src/logarithm.o
CXX     poincare/src/matrix.o
CXX     poincare/src/matrix_data.o
CXX     poincare/src/matrix_dimension.o
CXX     poincare/src/matrix_inverse.o
CXX     poincare/src/matrix_trace.o
CXX     poincare/src/matrix_transpose.o
CXX     poincare/src/multiplication.o
CXX     poincare/src/naperian_logarithm.o
CXX     poincare/src/nth_root.o
CXX     poincare/src/opposite.o
CXX     poincare/src/parenthesis.o
CXX     poincare/src/permute_coefficient.o
CXX     poincare/src/power.o
CXX     poincare/src/prediction_interval.o
CXX     poincare/src/preferences.o
CXX     poincare/src/product.o
CXX     poincare/src/reel_part.o
CXX     poincare/src/round.o
CXX     poincare/src/sequence.o
CXX     poincare/src/sine.o
CXX     poincare/src/square_root.o
CXX     poincare/src/store.o
CXX     poincare/src/subtraction.o
CXX     poincare/src/sum.o
CXX     poincare/src/symbol.o
CXX     poincare/src/tangent.o
CXX     poincare/src/variable_context.o
CXX     poincare/src/layout/absolute_value_layout.o
CXX     poincare/src/layout/baseline_relative_layout.o
CXX     poincare/src/layout/bracket_layout.o
CXX     poincare/src/layout/condensed_sum_layout.o
CXX     poincare/src/layout/conjugate_layout.o
CXX     poincare/src/layout/expression_layout.o
CXX     poincare/src/layout/fraction_layout.o
CXX     poincare/src/layout/grid_layout.o
CXX     poincare/src/layout/horizontal_layout.o
CXX     poincare/src/layout/integral_layout.o
CXX     poincare/src/layout/nth_root_layout.o
CXX     poincare/src/layout/parenthesis_layout.o
CXX     poincare/src/layout/product_layout.o
CXX     poincare/src/layout/sequence_layout.o
CXX     poincare/src/layout/string_layout.o
CXX     poincare/src/layout/sum_layout.o
CC      python/src/py/mpstate.o
CC      python/src/py/nlrx86.o
CC      python/src/py/nlrx64.o
CC      python/src/py/nlrthumb.o
CC      python/src/py/nlrxtensa.o
CC      python/src/py/nlrsetjmp.o
CC      python/src/py/malloc.o
CC      python/src/py/gc.o
CC      python/src/py/qstr.o
CC      python/src/py/vstr.o
CC      python/src/py/mpprint.o
CC      python/src/py/unicode.o
CC      python/src/py/mpz.o
CC      python/src/py/reader.o
CC      python/src/py/lexer.o
CC      python/src/py/parse.o
CC      python/src/py/scope.o
CC      python/src/py/compile.o
CC      python/src/py/emitcommon.o
CC      python/src/py/emitbc.o
CC      python/src/py/asmbase.o
CC      python/src/py/asmx64.o
CC      python/src/py/asmx86.o
CC      python/src/py/asmthumb.o
CC      python/src/py/emitinlinethumb.o
CC      python/src/py/asmarm.o
CC      python/src/py/asmxtensa.o
CC      python/src/py/formatfloat.o
CC      python/src/py/parsenumbase.o
CC      python/src/py/parsenum.o
CC      python/src/py/emitglue.o
CC      python/src/py/persistentcode.o
CC      python/src/py/runtime.o
CC      python/src/py/runtime_utils.o
CC      python/src/py/scheduler.o
CC      python/src/py/nativeglue.o
CC      python/src/py/stackctrl.o
CC      python/src/py/argcheck.o
CC      python/src/py/warning.o
CC      python/src/py/map.o
CC      python/src/py/obj.o
CC      python/src/py/objarray.o
CC      python/src/py/objattrtuple.o
CC      python/src/py/objbool.o
CC      python/src/py/objboundmeth.o
CC      python/src/py/objcell.o
CC      python/src/py/objclosure.o
CC      python/src/py/objcomplex.o
CC      python/src/py/objdict.o
CC      python/src/py/objenumerate.o
CC      python/src/py/objexcept.o
CC      python/src/py/objfilter.o
CC      python/src/py/objfloat.o
CC      python/src/py/objfun.o
CC      python/src/py/objgenerator.o
CC      python/src/py/objgetitemiter.o
CC      python/src/py/objint.o
CC      python/src/py/objint_longlong.o
CC      python/src/py/objint_mpz.o
CC      python/src/py/objlist.o
CC      python/src/py/objmap.o
CC      python/src/py/objmodule.o
CC      python/src/py/objobject.o
CC      python/src/py/objpolyiter.o
CC      python/src/py/objproperty.o
CC      python/src/py/objnone.o
CC      python/src/py/objnamedtuple.o
CC      python/src/py/objrange.o
CC      python/src/py/objreversed.o
CC      python/src/py/objset.o
CC      python/src/py/objsingleton.o
CC      python/src/py/objslice.o
CC      python/src/py/objstr.o
CC      python/src/py/objstrunicode.o
CC      python/src/py/objstringio.o
CC      python/src/py/objtuple.o
CC      python/src/py/objtype.o
CC      python/src/py/objzip.o
CC      python/src/py/opmethods.o
CC      python/src/py/sequence.o
CC      python/src/py/stream.o
CC      python/src/py/binary.o
CC      python/src/py/builtinimport.o
CC      python/src/py/builtinevex.o
CC      python/src/py/builtinhelp.o
CC      python/src/py/modarray.o
CC      python/src/py/modbuiltins.o
CC      python/src/py/modcollections.o
CC      python/src/py/modgc.o
CC      python/src/py/modio.o
CC      python/src/py/modmath.o
CC      python/src/py/modcmath.o
CC      python/src/py/modmicropython.o
CC      python/src/py/modstruct.o
CC      python/src/py/modsys.o
CC      python/src/py/moduerrno.o
CC      python/src/py/modthread.o
CC      python/src/py/vm.o
CC      python/src/py/bc.o
CC      python/src/py/showbc.o
CC      python/src/py/smallint.o
CC      python/src/py/frozenmod.o
CC      python/src/py/emitnative.o
CC      python/port/port.o
python/port/port.c:53:52: warning: incompatible pointer types initializing 'mp_fun_kw_t' (aka 'void *(*)(unsigned long, void *const *, struct _mp_map_t *)') with an expression of
      type 'mp_obj_t (uint, const mp_obj_t *, mp_map_t *)' (aka 'void *(unsigned int, void *const *, struct _mp_map_t *)') [-Wincompatible-pointer-types]
MP_DEFINE_CONST_FUN_OBJ_KW(mp_builtin_open_obj, 1, mp_builtin_open);
                                                   ^~~~~~~~~~~~~~~
python/src/py/obj.h:301:87: note: expanded from macro 'MP_DEFINE_CONST_FUN_OBJ_KW'
        {{&mp_type_fun_builtin_var}, true, n_args_min, MP_OBJ_FUN_ARGS_MAX, .fun.kw = fun_name}
                                                                                      ^~~~~~~~
1 warning generated.
CXX     python/port/interrupt_helper.o
CC      python/port/modkandinsky.o
CXX     python/port/modkandinsky_impl.o
CC      python/port/mphalport.o
CXX     escher/src/alternate_empty_view_controller.o
CXX     escher/src/app.o
CXX     escher/src/buffer_text_view.o
CXX     escher/src/button.o
CXX     escher/src/button_row_controller.o
CXX     escher/src/chevron_view.o
CXX     escher/src/clipboard.o
CXX     escher/src/container.o
CXX     escher/src/dynamic_view_controller.o
CXX     escher/src/editable_text_cell.o
CXX     escher/src/even_odd_cell.o
CXX     escher/src/even_odd_buffer_text_cell.o
CXX     escher/src/even_odd_editable_text_cell.o
CXX     escher/src/even_odd_expression_cell.o
CXX     escher/src/even_odd_message_text_cell.o
CXX     escher/src/expression_table_cell.o
CXX     escher/src/expression_table_cell_with_pointer.o
CXX     escher/src/expression_view.o
CXX     escher/src/highlight_cell.o
CXX     escher/src/image_view.o
CXX     escher/src/invocation.o
CXX     escher/src/input_view_controller.o
CXX     escher/src/key_view.o
CXX     escher/src/list_view_data_source.o
CXX     escher/src/message_table_cell.o
CXX     escher/src/message_table_cell_with_buffer.o
CXX     escher/src/message_table_cell_with_chevron.o
CXX     escher/src/message_table_cell_with_chevron_and_message.o
CXX     escher/src/message_table_cell_with_chevron_and_expression.o
CXX     escher/src/message_table_cell_with_editable_text.o
CXX     escher/src/message_table_cell_with_message.o
CXX     escher/src/message_table_cell_with_switch.o
CXX     escher/src/message_text_view.o
CXX     escher/src/modal_view_controller.o
CXX     escher/src/palette.o
CXX     escher/src/responder.o
CXX     escher/src/run_loop.o
CXX     escher/src/scroll_view.o
CXX     escher/src/scroll_view_data_source.o
CXX     escher/src/scroll_view_indicator.o
CXX     escher/src/scrollable_view.o
CXX     escher/src/selectable_table_view.o
CXX     escher/src/selectable_table_view_data_source.o
CXX     escher/src/selectable_table_view_delegate.o
CXX     escher/src/simple_list_view_data_source.o
CXX     escher/src/simple_table_view_data_source.o
CXX     escher/src/solid_color_view.o
CXX     escher/src/stack_view.o
CXX     escher/src/stack_view_controller.o
CXX     escher/src/switch_view.o
CXX     escher/src/tab_view.o
CXX     escher/src/tab_view_cell.o
CXX     escher/src/tab_view_controller.o
CXX     escher/src/tab_view_data_source.o
CXX     escher/src/table_cell.o
CXX     escher/src/table_view.o
CXX     escher/src/table_view_data_source.o
CXX     escher/src/text_cursor_view.o
CXX     escher/src/text_area.o
CXX     escher/src/text_field.o
CXX     escher/src/text_view.o
CXX     escher/src/tiled_view.o
CXX     escher/src/toolbox.o
CXX     escher/src/timer.o
CXX     escher/src/view.o
CXX     escher/src/view_controller.o
CXX     escher/src/warning_controller.o
CXX     escher/src/window.o
LD      app.elf
arm-none-eabi-gdb -x gdb_script.gdb app.elf
GNU gdb (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 7.12.1.20170417-git
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-apple-darwin10 --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
"/Users/dean/Documents/github/blackketter/epsilon/app.elf": not in executable format: File format not recognized
gdb_script.gdb:2: Error in sourced command file:
localhost:3333: Operation timed out.
(gdb) quit 
```

**Comment by adriweb** [comment]
I had the same issue - in fact for now you can just launch it directly running the binary (`./app.elf`, which isn't actually an ELF file but a Mach-O file as expected)
It will look like this:
![screenshot](https://i.imgur.com/KkYpryr.png)

**Comment by blackketter** [comment]
Awesome, thanks, works like a charm.  

I suggest that the technical documentation be included on GitHub with the source so that it can be updated via PR here.

**Comment by adriweb** [comment]
I agree that having the website (or at least the static one, not necessarily the workshop, for instance) as a GitHub repo too could be useful.
But anyway, in this case, it's probably the makefile that should be fixed, not the doc :)

**Comment by jacobly0** [comment]
You have to do `make PLATFORM=simulator app_run` for it to choose the native gdb over the cross arm one, so the "Installing the SDK" instructions should probably be changed.  In my case even if I do `GDB=gdb` so that it chooses lldb over gdb, I still get an error on line 2 of the gdb script.  In any case, the instructions should probably mention that you can also just run the executable.

**Comment by Ecco** [comment]
We eventually updated both the Makefile and the [documentation](https://www.numworks.com/resources/engineering/software/sdk/) 😄
